Add multi-site topic
AdobeDocs/commerce-pwa-studio pull request #107
Opened 2022-02-09 16:50 UTC by dobooth

## Description

This PR adds a topic for multi-site setup for PWA/UPWARD

## Related Issue

https://jira.corp.magento.com/browse/PWA-2562

2022-02-09 18:26 UTC, tjwiebell requested changes
Good starting point. Once theming work is closer to landing we can expand the use cases to include that scenario.

I'm not sure about the location, since this topic is specific to upward-php, and really only used in cloud environments. Thinking it should colocate closer to the [Deploy to Adobe Commerce](https://developer.adobe.com/commerce/pwa-studio/tutorials/production-deployment/adobe-commerce/) tutorial.

2022-02-09 18:26 UTC, tjwiebell commented on src/pages/guides/packages/upward/multi-site.md
> +CONFIG__WEBSITES__GERMAN__WEB__UPWARD__PATH=./dist-german/upward.yml
```suggestion
bin/magento pwa:upward:set --path ./dist-french/upward.yml --scopeType website --scopeCode fr
bin/magento pwa:upward:set --path ./dist-german/upward.yml --scopeType website --scopeCode de
```

2022-02-09 18:26 UTC, tjwiebell commented on src/pages/guides/packages/upward/multi-site.md
> +Setting up a PWA site with a Magento Open Source/Adobe Commerce backend is a straightforward process. This topic discusses how to server multiple PWA sites through a single backend.
```suggestion
Setting up a PWA site with a Magento Open Source/Adobe Commerce backend is a straightforward process. This topic discusses how to serve multiple PWA sites through a single backend.
```

2022-02-14 18:33 UTC, tjwiebell approved these changes

2022-02-16 15:01 UTC, bdenham approved these changes
So I went through this as the newbie I am—but unfortunately, I don't have a running instance at the moment to test and walk through things as I would normally do. 

@tjwiebell : Can you make sure my changes are still correct? I made some assumptions that I'm not yet sure about. Thanks!

Approved pending @tjwiebell's review and any requested updates.

2022-02-16 15:01 UTC, bdenham commented on src/pages/guides/packages/upward/multi-site.md
> +Setting up a PWA site with a Magento Open Source/Adobe Commerce backend is a straightforward process. This topic discusses how to serve multiple PWA sites through a single backend.
```suggestion
This topic describes how to configure your UPWARD server to run multiple PWA sites from a single Magento Open Source or Adobe Commerce backend.
```

2022-02-16 15:01 UTC, bdenham commented on src/pages/guides/packages/upward/multi-site.md
> +PWA Studio 12.2.0 ships with the `magento2-upward-connector` extension. This module allows the running of multiple PWA instances off a Magento/Adobe Commerce instance. It also provides CLI commands t
```suggestion
When you use the PWA scaffolding tool to create a PWA Studio project, one of the many modules installed is the UPWARD PHP connector module—`magento2-upward-connector`. This module provides a CLI to help you configure different PWA sites to run from a single Commerce or Open Source server.
```

2022-02-16 15:01 UTC, bdenham commented on src/pages/guides/packages/upward/multi-site.md
> +        'default' => '/var/www/html/pwa/dist/upward.yml'
```suggestion
        'default' => '/var/www/html/my-pwa-site/dist/upward.yml'
```

2022-02-16 15:01 UTC, bdenham commented on src/pages/guides/packages/upward/multi-site.md
> +        '<website_code>' => '/var/www/html/anotherpwa/dist/upward.yml'
```suggestion
        '<website_code>' => '/var/www/html/my-awesome-pwa-site/dist/upward.yml'
```

2022-02-16 15:01 UTC, bdenham commented on src/pages/guides/packages/upward/multi-site.md
> +This module works by adding a directive to `env.php` which sets a path to the `upward.yaml` file.
```suggestion
## Configuring the UPWARD server

The first step is to configure the UPWARD server to access the different PWA sites you want to deploy. And the CLI provided by the UPWARD module is how you do it. 

But before we get to the specifics, here's the overview of what you are actually doing. When you execute the CLI commands, you're actually adding `pwa_paths` to the `env.php` file. The commands specify the paths to the `upward.yml` configuration for each PWA site you want to deploy. The following  example shows what an `env.php` configuration file may look like AFTER using the CLI to add two different PWA sites to the `default` and `website` configurations:
```

2022-02-16 15:01 UTC, bdenham commented on src/pages/guides/packages/upward/multi-site.md
> +        '<store_code>' => '' # Use a blank string (or false) to serve the default Magento storefront
```suggestion
        '<store_code>' => '' # Setting an empty string (or `false` value) will serve the specified default site (my-pwa-site)
```

2022-02-16 15:01 UTC, bdenham commented on src/pages/guides/packages/upward/multi-site.md
> +### CLI usage
```suggestion
## Using UPWARD CLI commands
```

2022-02-16 15:01 UTC, bdenham commented on src/pages/guides/packages/upward/multi-site.md
> +Use the CLI commands to set the parameters for your PWA store.
```suggestion
The UPWARD module commands provide a convenient way to configure the server to deploy different PWA sites. The following examples show common usage patterns.
```

2022-02-16 15:01 UTC, bdenham commented on src/pages/guides/packages/upward/multi-site.md
> +This example sets the path to the UPWARD yaml file and provides the `scopeType` and `scopeCode` values.
```suggestion

**Set UPWARD paths with `scopeType` and `scopeCode`:**
```

2022-02-16 15:01 UTC, bdenham commented on src/pages/guides/packages/upward/multi-site.md
> +You can use `bin/magento store:list` or `bin/magento store:website:list` to retrieve the store/website values.
```suggestion
To find the paths of your PWA sites (by scope) as shown above for the store scope, use one of the following commands:
-  `bin/magento store:list` (for store scope)
-  `bin/magento store:website:list` (for store and website scopes)
```

2022-02-16 15:01 UTC, bdenham commented on src/pages/guides/packages/upward/multi-site.md
> +bin/magento pwa:upward:set
I can't walk through this myself at the moment, but wondering if this command must be followed by an actual empty string (`''`) or `false` as described previously?

2022-02-16 15:01 UTC, bdenham commented on src/pages/guides/packages/upward/multi-site.md
> +The configuration works the same way as a normal store configuration: It falls back from store view > website > global (default), trying to serve the most specific available scope first.
```suggestion
The UPWARD path configurations work the same as other store configurations: The config settings fall up in scope from `store` > `website` > `global` (default), trying to serve the most specific, available site scope first.
```

2022-02-16 15:01 UTC, bdenham commented on src/pages/guides/packages/upward/multi-site.md
> +It is possible to generate unique bundles per website within a single scaffold.
```suggestion
You can also generate unique bundles per website within a single scaffolded project.

For example, if you want to deploy both French and German versions of your site, you could use the following commands to configure your UPWARD server:
```

2022-02-16 15:01 UTC, bdenham commented on src/pages/guides/packages/upward/multi-site.md
> +A single UPWARD server is capable of processing requests for each website bundle.
```suggestion
With this configuration, a single UPWARD server can process requests for many different website bundles.
```

2022-02-17 13:07 UTC, bdenham commented on src/pages/guides/packages/upward/multi-site.md
> +bin/magento pwa:upward:set
@tjwiebell can you verify the command above?

2022-02-17 13:29 UTC, merged