PWA 12.5 docs
AdobeDocs/commerce-pwa-studio pull request #143
Opened 2022-06-15 19:22 UTC by dobooth

## Description

This PR contains content for the PWA 12.5 release, focusing on the new eventing framework.

## Affected Pages

https://developer.adobe.com/commerce/pwa-studio/integrations/analytics/
https://developer.adobe.com/commerce/pwa-studio/integrations/analytics/custom-events
https://developer.adobe.com/commerce/pwa-studio/integrations/analytics/event-reference
https://developer.adobe.com/commerce/pwa-studio/integrations/analytics/installation-and-configuration

## Issue/Ticket Number

[PWA](https://jira.corp.magento.com/browse/PWA-2365)

2022-06-15 19:49 UTC, jcalcaben requested changes
Is there a topic that describes the core eventing framework that the analytics extension taps into?

2022-06-15 19:49 UTC, jcalcaben commented on src/pages/integrations/analytics/custom-events/index.md
> +In the sample extension, the `SEARCH_REPSONSE` event is being tracked. This event is fired when a search result is returned from the Adobe Experience Manager (AEM), with either results or a `EMPTY_RE
* I hope it's not spelled `SEARCH_REPSONSE` in the codebase 😬 
* the event is fired when Magento returns search results data, not AEM

2022-06-15 19:49 UTC, jcalcaben commented on src/pages/integrations/analytics/custom-events/index.md
> +This file sets the payload and the search results context. The custom event name is also defined in this file.
Seems to be a lot of relevant code missing from this snippet.

Also, I would describe this file as an event handler file that returns two functions:

1. `canHandle()` - a function that receives an event from PWA Studio's eventing framework and returns true if the `handle()` function in this file should handle the incoming event
2. `handle()` - function that handles the event

2022-06-15 19:49 UTC, jcalcaben commented on src/pages/integrations/analytics/custom-events/index.md
> +title: Custom events for Beacon analytics
the official name is Experience Platform(I think), not Beacon

2022-06-15 19:49 UTC, jcalcaben commented on src/pages/integrations/analytics/custom-events/index.md
> +In `wrapUseAutocomplete.js` the search result is received and the payload defined and dispatched. This take place in the `useEffect` function:
Would describe this file as a talon wrapper that wraps around the `useAutocomplete()` talon to add event dispatching logic.

Would link to doc page about [talons](https://developer.adobe.com/commerce/pwa-studio/guides/general-concepts/talons/), tutorial on [how to wrap a talon](https://developer.adobe.com/commerce/pwa-studio/tutorials/targets/modify-talon-results/), and whatever docs we have about the eventing framework.

2022-06-15 19:49 UTC, jcalcaben commented on src/pages/integrations/analytics/custom-events/index.md
> +```javascript
Missing a lot of relevant code

2022-06-15 19:49 UTC, jcalcaben commented on src/pages/integrations/analytics/custom-events/index.md
> +Edit copy of `intercept.js` to pull in the custom extension by name. In this case, the `SearchBar` wrapper:
This is an intercept file that interacts with PWA Studio's extensibility framework to modify code during build time.
In this particular code, the `useApp()`, `useAccountMenu()`, and `useAutocomplete()` talons are wrapped with modules that provide additional logic.

Would link to:
* [docs on extensibility](https://developer.adobe.com/commerce/pwa-studio/guides/general-concepts/extensibility/)
* [modify talons tutorial](https://developer.adobe.com/commerce/pwa-studio/tutorials/targets/modify-talon-results/)

2022-06-15 19:49 UTC, jcalcaben commented on src/pages/integrations/analytics/custom-events/index.md
> +## Import a custom extension
Not sure this is needed. Most developers should already know how to set up a new package but if you really want to start from scratch, I would refer to the section in this tutorial on [how to initialize a project](https://developer.adobe.com/commerce/pwa-studio/tutorials/targets/modify-talon-results/#initialize-the-project).

I would replace this particular section with a testing locally section that looks like [this](https://developer.adobe.com/commerce/pwa-studio/tutorials/targets/modify-talon-results/#test-on-a-local-instance)

2022-06-20 18:17 UTC, bdenham requested changes
See changes.

2022-06-20 18:17 UTC, bdenham commented on src/pages/guides/general-concepts/analytics/index.md
> +PWA Studio emits a series of events for for use in analytics.
```suggestion
PWA Studio emits a series of events for use in Adobe Analytics.
```

2022-06-20 18:17 UTC, bdenham commented on src/pages/guides/general-concepts/analytics/index.md
> +| Page View |	A specific page has been navigated to by the end user |	virtualPageView	 ||
```suggestion
| Page View | Triggered when the site displays any page to the user.  | virtualPageView ||
```

2022-06-20 18:17 UTC, bdenham commented on src/pages/guides/general-concepts/analytics/index.md
> +| Product Detail Page View | The product detail page has been navigated to by the end user | productDetail ||
```suggestion
| Product Detail Page View | Triggered when the site displays a product-detail page. | productDetail ||
```

2022-06-20 18:17 UTC, bdenham commented on src/pages/guides/general-concepts/analytics/index.md
> +| Product Impression | A specific product has been shown to the end user | productImpression |
```suggestion
| Product Impression | Triggered when the site displays a product on the page. | productImpression |
```

2022-06-20 18:17 UTC, bdenham commented on src/pages/guides/general-concepts/analytics/index.md
> +| Product Click | A specific product has been clicked on by the end user | productClick ||
```suggestion
| Product Click | Triggered when a user clicks a product link on the page. | productClick ||
```

2022-06-20 18:17 UTC, bdenham commented on src/pages/guides/general-concepts/analytics/index.md
> +| Add to Cart | A product has been added to the cart by the end user | add-to-cart | |
```suggestion
| Add to Cart | Triggered when a user adds an item to the cart. | add-to-cart | |
```

2022-06-20 18:17 UTC, bdenham commented on src/pages/guides/general-concepts/analytics/index.md
> +
Update this table to match the wording structure used above.

2022-06-20 18:17 UTC, bdenham commented on src/pages/integrations/analytics/custom-events/index.md
> +PWA Studio 12.5 contains an eventing framework with a series of default events that cover common scenarios.
```suggestion
PWA Studio 12.5 adds an eventing framework to capture a set of default, everyday shopper interactions on your storefronts.
```

2022-06-20 18:17 UTC, bdenham commented on src/pages/integrations/analytics/custom-events/index.md
> +By creating and importing a custom extension, it is possible to add new events so that you may track specific user interactions beyond what is included in the default package.
```suggestion
You can also extend the framework by adding additional events to track user interactions beyond those in the default package.
```

2022-06-20 18:17 UTC, bdenham commented on src/pages/integrations/analytics/custom-events/index.md
> +In the sample extension, the `SEARCH_RESPONSE` event is being tracked. This event is fired when a search result is returned from Adobe Commerce, with either results or a `EMPTY_RESULT` response.
```suggestion
In this sample extension, we added a `SEARCH_RESPONSE` event. This event fires when a search result or an `EMPTY_RESULT` response is returned from Adobe Commerce.
```

2022-06-20 18:17 UTC, bdenham commented on src/pages/integrations/analytics/custom-events/index.md
> +These files can be used as a starting point for a custom event extension.
```suggestion
These files can be used as a starting point to create your own custom events.
```

2022-06-20 18:17 UTC, bdenham commented on src/pages/integrations/analytics/custom-events/index.md
> +In `wrapUseAutocomplete.js` the search result is received and the payload defined and dispatched. This take place in the `useEffect` function:
I defer to James here.

2022-06-20 18:17 UTC, bdenham commented on src/pages/integrations/analytics/custom-events/index.md
> +```javascript
Deferring to James.

2022-06-20 18:17 UTC, bdenham commented on src/pages/integrations/analytics/index.md
> +The following topics describe how to install, configure and customize analytics to your specific needs.
```suggestion
The following topics describe how to install, configure, and customize analytics to your specific needs.
```

2022-06-20 18:17 UTC, bdenham commented on src/pages/integrations/analytics/installation-and-configuration/index.md
> +```json
```suggestion
```terminal
```

2022-06-20 18:17 UTC, bdenham commented on src/pages/integrations/analytics/installation-and-configuration/index.md
> +The Experience Platform analytics endpoint needs to be setup with the Adobe Commerce admin.
```suggestion
The Experience Platform analytics endpoint needs to be set up in the Adobe Commerce Admin UI.
```

2022-06-20 18:17 UTC, bdenham commented on src/pages/integrations/analytics/subscribe/index.md
> +3rd party modules can subscribe to events, allowing you to use other analytics collections schemes.
```suggestion
Third-party modules can subscribe to events, allowing you to use other analytics collection schemes.
```

2022-06-20 20:11 UTC, bdenham approved these changes
Couple more changes. Approved on edit.

2022-06-20 20:11 UTC, bdenham commented on src/pages/integrations/analytics/index.md
> +
```suggestion

# Experience Platform analytics in PWA Studio

```

2022-06-20 20:11 UTC, bdenham commented on src/pages/guides/general-concepts/analytics/index.md
> +## PWA analytics
```suggestion
# Analytics events
```

2022-06-24 17:19 UTC, jcalcaben requested changes

2022-06-24 17:19 UTC, jcalcaben commented on src/pages/guides/general-concepts/eventing/index.md
> +The Adobe Commerce backend can be [configured](/integrations/adobe-commerce/aep/) to send event data to the Adobe Experience Platform.
```suggestion
The extension requires the Adobe Commerce backend to be properly [configured](/integrations/adobe-commerce/aep/) before it can send event data to the Adobe Experience Platform.
```

2022-06-24 17:19 UTC, jcalcaben commented on src/pages/guides/general-concepts/eventing/index.md
> +The eventing framework uses observables: a mechanism to pass messages between parts of an application.
it's really just a single observable state so I would refer to it in the singular sense unless you're talking about the concept of observables, in which case it's fine to use the plural here but it does make it less clear/accurate

Suggested change:

> At the core of the eventing framework is an [observable](/link/to/relevant/external/doc).
> When extensions subscribe to the observable the framework notifies it whenever the application publishes an event and sends the event data to the extension for handling.

2022-06-24 17:19 UTC, jcalcaben commented on src/pages/integrations/adobe-commerce/aep/index.md
> +PWA Studio 12.5.0 has an eventing framework that allows store owners to track user interaction with their site and return analytics information.
```suggestion
Included in the PWA Studio 12.5.0 release is an eventing framework that lets store owners install extensions that track user interaction within their site and collect analytics information.
```

2022-06-24 17:19 UTC, jcalcaben commented on src/pages/integrations/adobe-commerce/aep/index.md
> +With the Experience Platform extension, Adobe Commerce users with an Adobe Experience Platform (AEP) subscription can get event data from PWA sites and process it on the AEP.
```suggestion
With the Experience Platform Connector extension, Adobe Commerce users with an Adobe Experience Platform (AEP) subscription can get event data from PWA Studio storefronts and process it on the AEP.
```

2022-06-24 17:19 UTC, jcalcaben commented on src/pages/integrations/adobe-commerce/aep/index.md
> +There are two pieces required to get event data to the AEP:
```suggestion
This integration requires the following pieces to function properly:
```

2022-06-24 17:19 UTC, jcalcaben commented on src/pages/integrations/adobe-commerce/aep/index.md
> +- The Experience Platform Connector is an extension for Adobe Commerce that connects to the AEP platform.
```suggestion
- The Experience Platform Connector extension for PWA Studio storefronts, which connects and send data to the AEP platform.
- The Experience Platform extensions installed in the Adobe Commerce backend which provides configuration information to the storefront extension.
```

A link to where to find the list of required backend extension would be helpful here too.

2022-06-24 17:19 UTC, jcalcaben commented on src/pages/integrations/adobe-commerce/aep/index.md
> +Magento Open Source does not support the AEP.
I would bring more attention to this callout. Do we still use info or warning boxes in our docs?

2022-06-24 17:19 UTC, jcalcaben commented on src/pages/integrations/adobe-commerce/aep/index.md
> +This document describes how to install the Experience Platform extension and how to configure Adobe Commerce to receive event data.
```suggestion
The following sections provide installation and configuration instructions for the Experience Platform integration.
```

2022-06-24 17:19 UTC, jcalcaben commented on src/pages/integrations/adobe-commerce/aep/index.md
> +The Experience Platform extension uses the standard Composer-based installation method.
```suggestion
Use your storefront project's package manager(`node` or `yarn`), to install the Experience Platform Connector extension into your storefront project.
```

2022-06-24 17:19 UTC, jcalcaben commented on src/pages/integrations/adobe-commerce/aep/index.md
> +Open your `yarn` file and add the following line:
```suggestion
For example, if your project uses `yarn` run the following command: 
```

2022-06-24 17:19 UTC, jcalcaben commented on src/pages/tutorials/events/custom-events/index.md
> +PWA Studio 12.5 adds an eventing framework to capture a set of default, everyday shopper interactions on your storefronts.
```suggestion
The eventing framework introduced in the PWA Studio 12.5 release comes with a core set of storefront events related to various interactions with the application.
```

2022-06-24 17:19 UTC, jcalcaben commented on src/pages/tutorials/events/custom-events/index.md
> +You can also extend the framework by adding additional events to track user interactions beyond those in the default package.
```suggestion
You can use PWA Studio's extensibility framework to modify your storefront and have it publish events not covered by the default set.
```

2022-06-24 17:19 UTC, jcalcaben commented on src/pages/tutorials/events/custom-events/index.md
> +PWA Studio provides a [sample extension](https://github.com/magento/pwa-studio/tree/develop/packages/extensions/experience-platform-connector/) that shows how to add a custom event.
```suggestion
PWA Studio provides the source for the [Experience Platform Connector extension](https://github.com/magento/pwa-studio/tree/develop/packages/extensions/experience-platform-connector/) to show how you can add a custom event.
```

2022-06-24 17:19 UTC, jcalcaben commented on src/pages/tutorials/events/custom-events/index.md
> +In this sample extension, we added a `SEARCH_RESPONSE` event. This event fires when a search result or an `EMPTY_RESULT` response is returned from Adobe Commerce.
```suggestion
This extension dispatches a `SEARCH_RESPONSE` event, which is not part of the default set. This event fires when a search result is returned in the application's search bar.
```

2022-06-24 17:19 UTC, jcalcaben commented on src/pages/tutorials/events/custom-events/index.md
> +These files can be used as a starting point to create your own custom events.
```suggestion
These files show the different pieces and logic you need to create your own custom events.
```

2022-06-27 18:26 UTC, jcalcaben approved these changes

2022-06-28 15:33 UTC, merged